Repository A3Data/pyspark-notebook-helm, pull requests merged in 2022-02, with the labels that each got.

#5 Reorganized project directory structure and add automate releasing charts
  .github/workflows/lint-test.yml
  .github/workflows/release.yml
  .gitignore
  charts/pyspark-notebook/.helmignore
  charts/pyspark-notebook/Chart.yaml
  charts/pyspark-notebook/README.md
  charts/pyspark-notebook/templates/NOTES.txt
  charts/pyspark-notebook/templates/_helpers.tpl
  charts/pyspark-notebook/templates/ingress.yaml
  charts/pyspark-notebook/templates/role.yaml
  charts/pyspark-notebook/templates/rolebinding.yaml
  charts/pyspark-notebook/templates/service.yaml
  charts/pyspark-notebook/templates/serviceaccount.yaml
  charts/pyspark-notebook/templates/statefulset.yaml
  charts/pyspark-notebook/values.yaml
  cr.yaml
  ct.yaml
  templates/tests/test-connection.yaml
Labels: enhancement

#8 Fix EKS Persistence
  charts/pyspark-notebook/Chart.yaml
  charts/pyspark-notebook/values.yaml
Labels: bug

#10 doc/aws-example
  README.md
  charts/pyspark-notebook/Chart.yaml
  charts/pyspark-notebook/README.md
Labels: documentation
